import 'dart:convert';
import 'dart:math';
import 'package:crypto/crypto.dart';
import 'package:danawallet/data/models/bip353_address.dart';
import 'package:danawallet/data/models/prefix_search_response.dart';
import 'package:danawallet/exceptions.dart';
import 'package:danawallet/extensions/bip321_uri.dart';
import 'package:danawallet/generated/rust/api/bip39.dart';
import 'package:danawallet/generated/rust/api/structs/network.dart';
import 'package:danawallet/repositories/name_server_repository.dart';
import 'package:danawallet/services/bip353_resolver.dart';
import 'package:logger/logger.dart';

class DanaAddressService {
  NameServerRepository nameServerRepository;
  final Network network;
  final Random _random = Random.secure();
  String? _domain;

  DanaAddressService({required this.network})
      : nameServerRepository = NameServerRepository(network: network);

  Future<String> get danaAddressDomain async {
    // lazy initialization of domain
    _domain ??= (await nameServerRepository.getInfo()).domain;

    return _domain!;
  }

  /// Generates a unique ID for requests without external dependencies
  /// Format: timestamp-randomhex (e.g., "1699889234567-a3f2c9d8")
  String _generateUniqueId() {
    final timestamp = DateTime.now().microsecondsSinceEpoch;
    final randomHex =
        _random.nextInt(0xFFFFFFFF).toRadixString(16).padLeft(8, '0');
    return '$timestamp-$randomHex';
  }

  /// Generates a deterministic 3-word alias from entropy using BIP39 wordlist
  /// The alias is generated by using the entropy bytes to select words
  /// [entropy] - The entropy bytes (typically from a SHA-256 hash)
  /// [offset] - Byte offset into the entropy (0, 6, 12, 18, etc.) to use different parts
  String _generateRandomDanaAddress(
      {required String paymentCode, required int offset}) {
    final entropy = _generateEntropyFromPaymentCode(paymentCode);

    final wordlist = getEnglishWordlist();
    final wordlistSize = wordlist.length;

    // Ensure we have enough bytes for the offset
    if (offset + 6 > entropy.length) {
      // If offset is too large, wrap around using modulo
      offset = offset % (entropy.length - 5);
    }

    // Use different parts of the entropy to select 2 words and 1 number
    // This ensures deterministic selection while avoiding collisions
    final word1Index =
        (entropy[offset] << 8 | entropy[offset + 1]) % wordlistSize;
    final word2Index =
        (entropy[offset + 2] << 8 | entropy[offset + 3]) % wordlistSize;
    final numericValue =
        (entropy[offset + 4] << 8 | entropy[offset + 5]) % 1000;

    return '${wordlist[word1Index]}-${wordlist[word2Index]}-$numericValue';
  }

  /// Generates entropy (SHA-256 hash) from an address
  List<int> _generateEntropyFromPaymentCode(String paymentCode) {
    final bytes = utf8.encode(paymentCode);
    final hash = sha256.convert(bytes);
    return hash.bytes;
  }

  /// Generate an available dana address by trying different username candidates
  /// Returns the first available username found within maxRetries attempts, or null if all are taken
  Future<String?> generateAvailableDanaAddress({
    required String paymentCode,
    required int maxRetries,
  }) async {
    for (int attempt = 0; attempt < maxRetries; attempt++) {
      final username = _generateRandomDanaAddress(
        paymentCode: paymentCode,
        offset:
            attempt * 6, // Each attempt uses 6 bytes (2 bytes per word/number)
      );
      final isAvailable = await isDanaUsernameAvailable(username);
      if (isAvailable) {
        return username;
      }
    }
    return null;
  }

  /// Registers [username] on the dana address domain for [paymentCode].
  ///
  /// Resolves the name first: if it already points at [paymentCode], returns
  /// that address with no name-server call; if it points elsewhere, throws;
  /// if it is unregistered, registers via the name server.
  ///
  /// Returns the registered [Bip353Address].
  Future<Bip353Address> registerUser({
    required String username,
    required String paymentCode,
  }) async {
    final requestId = _generateUniqueId();
    final domain = await danaAddressDomain;
    final danaAddress = Bip353Address(username: username, domain: domain);

    // We try to resolve the address first to see if it already exists
    try {
      final bip321Uri = await Bip353Resolver.resolveParsed(danaAddress);
      final resolvedPaymentCode =
          bip321Uri.reusablePaymentCodeForNetwork(network);
      if (resolvedPaymentCode == null) {
        throw Bip353InvalidRecordException(
            "$danaAddress exists but doesn't contain payment code");
      } else if (resolvedPaymentCode == paymentCode) {
        return danaAddress;
      } else {
        throw Bip353AddressAlreadyUsed(
            address: danaAddress, resolved: resolvedPaymentCode);
      }
    } on Bip353AddressNotRegisteredException {
      Logger().i(
          'Address $username@$domain not found, proceeding with registration');
      return await nameServerRepository.registerDanaAddress(
          danaAddress: danaAddress,
          paymentCode: paymentCode,
          requestId: requestId);
    }
  }

  /// Looks up dana addresses associated with a silent payment address.
  /// Also verifies if the returned Dana address by doing a DNS query
  ///
  /// [paymentCode] - The Silent Payment address to lookup
  ///
  /// Returns the first valid dana address that is found.
  /// Returns a list of dana addresses in the format `user_name@danawallet.app`
  /// Returns an empty list if no addresses are found
  /// Throws an exception for network errors, invalid responses, or malformed data
  Future<Bip353Address?> lookupDanaAddress(String paymentCode) async {
    if (paymentCode.isEmpty) {
      throw ArgumentError("Silent payment address cannot be empty");
    }

    final requestId = _generateUniqueId();
    final addresses =
        await nameServerRepository.lookupDanaAddresses(paymentCode, requestId);

    Logger().i('Found ${addresses.length} dana address(es) for SP address');

    for (var candidate in addresses) {
      try {
        final bip321Uri = await Bip353Resolver.resolveParsed(candidate);
        final resolved = bip321Uri.reusablePaymentCodeForNetwork(network);
        if (resolved == null) {
          throw Bip353PaymentCodeMismatchException(
              address: candidate, expected: paymentCode, resolved: null);
        } else if (resolved != paymentCode) {
          // If this happen something's wrong with the nameserver
          throw Bip353PaymentCodeMismatchException(
              address: candidate, expected: paymentCode, resolved: resolved);
        }
        // No exception means the candidate resolves to our payment code.
        return candidate;
      } catch (e) {
        Logger().w("Skipping $candidate: $e");
      }
    }
    return null;
  }

  /// Check if a dana address is available for registration
  /// Returns true if the dana address is not taken, false otherwise
  Future<bool> isDanaUsernameAvailable(String username) async {
    try {
      final domain = await danaAddressDomain;
      final bip353Address = Bip353Address(username: username, domain: domain);
      await Bip353Resolver.resolveParsed(bip353Address);
      // If we can resolve something then the entry exists
      // We could check if the bip321 uri actually contains a payment code
      // but I think that in that case it doesn't really matter
      // We can't register the entry
      return false;
    } on Bip353AddressNotRegisteredException {
      return true;
    } catch (e) {
      Logger().e('Error checking address availability: $e');
      return false;
    }
  }

  /// Searches for dana addresses by prefix
  ///
  /// [prefix] - The prefix to search for (e.g., "alice" to find "alice@domain.com")
  ///
  /// Returns [PrefixSearchResponse] with matching dana addresses
  /// Throws an exception for network errors, invalid responses, or malformed data
  Future<List<Bip353Address>> searchPrefix(String prefix) async {
    if (prefix.isEmpty) {
      throw ArgumentError("Prefix cannot be empty");
    }

    try {
      final requestId = _generateUniqueId();
      final response = await nameServerRepository.searchDanaAddressesWithPrefix(
          prefix, requestId);
      return response.danaAddresses;
    } catch (e) {
      Logger().e('Prefix search request failed for prefix "$prefix": $e');
      throw Exception('Prefix search request failed: $e');
    }
  }
}
